.TH "qwt_plot_dict.h" 3 "24 May 2008" "Version 5.1.1" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qwt_plot_dict.h \- 
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBqwt_plot_dict.h\fP.
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQwtPlotDict\fP"
.br
.RI "\fIA dictionary for plot items. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QList< \fBQwtPlotItem\fP * >::ConstIterator \fBQwtPlotItemIterator\fP"
.br
.ti -1c
.RI "typedef QList< \fBQwtPlotItem\fP * > \fBQwtPlotItemList\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QList< \fBQwtPlotItem\fP * > \fBQwtPlotItemList\fP"
.PP
See QT 4.x assistant documentation for QList. 
.PP
Definition at line 30 of file qwt_plot_dict.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
