.TH "qwt_double_rect.h" 3 "24 May 2008" "Version 5.1.1" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qwt_double_rect.h \- 
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBqwt_double_rect.h\fP.
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBQWT_DOUBLE_RECT_H\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QPointF \fBQwtDoublePoint\fP"
.br
.ti -1c
.RI "typedef QSizeF \fBQwtDoubleSize\fP"
.br
.ti -1c
.RI "typedef QRectF \fBQwtDoubleRect\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "QPointF \fBQwtDoublePoint\fP"
.PP
This is a typedef, see Trolltech Documentation for QPointF in QT assistant 4.x. As soon as Qt3 compatibility is dropped this typedef will disappear. 
.PP
Definition at line 29 of file qwt_double_rect.h.
.SS "QRectF \fBQwtDoubleRect\fP"
.PP
This is a typedef, see Trolltech Documentation for QRectF in QT assistant 4.x. As soon as Qt3 compatibility is dropped this typedef will disappear. 
.PP
Definition at line 45 of file qwt_double_rect.h.
.SS "QSizeF \fBQwtDoubleSize\fP"
.PP
This is a typedef, see Trolltech Documentation for QSizeF in QT assistant 4.x. As soon as Qt3 compatibility is dropped this typedef will disappear. 
.PP
Definition at line 37 of file qwt_double_rect.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
