.TH "QwtClipper" 3 "24 May 2008" "Version 5.1.1" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtClipper \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Some clipping algos. 
.PP
Definition at line 25 of file qwt_clipper.h.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QwtPolygon \fBclipPolygon\fP (const QRect &, const QwtPolygon &)"
.br
.ti -1c
.RI "static QwtPolygonF \fBclipPolygonF\fP (const \fBQwtDoubleRect\fP &, const QwtPolygonF &)"
.br
.ti -1c
.RI "static QwtArray< \fBQwtDoubleInterval\fP > \fBclipCircle\fP (const \fBQwtDoubleRect\fP &, const \fBQwtDoublePoint\fP &, double radius)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
