.TH "QwtLegendItemManager" 3 "24 May 2008" "Version 5.1.1" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtLegendItemManager \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBQwtPlotItem\fP.
.PP
.SH "Detailed Description"
.PP 
Definition at line 20 of file qwt_legend_itemmanager.h.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtLegendItemManager\fP ()"
.br
.ti -1c
.RI "virtual \fB~QwtLegendItemManager\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdateLegend\fP (\fBQwtLegend\fP *) const =0"
.br
.ti -1c
.RI "virtual QWidget * \fBlegendItem\fP () const=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
